FROM ruby:2.5.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs postgresql-client-9.6 netcat

WORKDIR /opt/sabre

ADD ./Gemfile /opt/sabre/Gemfile
ADD ./Gemfile.lock /opt/sabre/Gemfile.lock

RUN bundle install  --jobs 20 --retry 5

COPY ./ ./

CMD ["bash", "start_server.sh"]
